# Generated by Django 5.1.6 on 2025-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_vegetables_vegetables_vegetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
