# Generated by Django 5.1.6 on 2025-02-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_product_description_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.shopimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopimage',
            name='image',
            field=models.ImageField(default=1, upload_to='shop/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='images',
            field=models.ImageField(null=True, upload_to='vegetables/'),
        ),
    ]
