# Generated by Django 5.1.6 on 2025-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_shop_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='shop/'),
        ),
    ]
