# Generated by Django 5.1.6 on 2025-02-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_shop_vegetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='vegetables',
        ),
    ]
