# Generated by Django 5.1.6 on 2025-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_shop_vegetables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize_per_kg',
            new_name='price_per_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
