# Generated by Django 5.1.6 on 2025-02-21 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_temp_user_vegetables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetables',
            old_name='product_name',
            new_name='vegetables',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='image',
        ),
        migrations.AddField(
            model_name='temp_user',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
