# Generated by Django 5.1.6 on 2025-02-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_shopimage_image_url_remove_shopimage_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.rating'),
        ),
    ]
