# Generated by Django 5.1.6 on 2025-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=2, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
