# Generated by Django 5.1.6 on 2025-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_shop_image_alter_rating_rating_alter_shop_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
