# Generated by Django 5.1.6 on 2025-02-21 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_remove_shop_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='vegetables',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='marketplace.vegetables'),
            preserve_default=False,
        ),
    ]
