# Generated by Django 5.1.3 on 2025-02-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
