# Generated by Django 5.1.3 on 2025-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_rating_shopimage_tempuser_vegetable_vegetableimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='image',
            field=models.ImageField(default=2, upload_to='default/vegetable_image'),
            preserve_default=False,
        ),
    ]
