# Generated by Django 5.1.3 on 2025-02-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_vegetable_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetableimage',
            old_name='image',
            new_name='images',
        ),
    ]
