# Generated by Django 5.1.3 on 2025-02-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_rename_image_vegetableimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetableimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='image',
        ),
        migrations.AddField(
            model_name='shop',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='vegetables/defaults/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
