# Generated by Django 5.1.3 on 2025-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_alter_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='vegetables',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=1, upload_to='shop/image/'),
            preserve_default=False,
        ),
    ]
