# Generated by Django 5.1.3 on 2025-02-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_remove_shop_vegetables_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=500, upload_to='shop/image/'),
        ),
    ]
