# Generated by Django 5.1.3 on 2025-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_delete_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_description',
            field=models.TextField(null=True),
        ),
    ]
