# Generated by Django 5.1.3 on 2025-02-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_alter_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
    ]
