# Generated by Django 5.1.3 on 2025-02-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_shop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='description',
            new_name='shop_description',
        ),
    ]
