# Generated by Django 5.1.3 on 2025-02-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_product_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='total_ratings',
        ),
    ]
