# Generated by Django 5.1.3 on 2025-02-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_remove_shop_average_rating_remove_shop_total_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
    ]
