# Generated by Django 5.1.3 on 2025-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_remove_rating_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
