# Generated by Django 5.1.3 on 2025-03-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='lifespan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
